#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir ~/.config/awesome
ln -sf $DIR"/config/awesome/rc.lua" ~/.config/awesome/rc.lua
ln -sf $DIR"/config/awesome/debian" ~/.config/awesome/debian

