#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $DIR
cd $DIR

if ! hash awesome
then
    sudo apt-get install awesome awesome-extra
fi

mkdir ~/.config/awesome
ln -sv $DIR"/config/awesome/rc.lua" ~/.config/awesome/rc.lua
ln -sv "$DIR""/config/awesome/debian" ~/.config/awesome/

