#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo $DIR
cd $DIR

if ! hash awesome
then
    sudo apt-get install awesome awesome-extra
fi

mkdir ~/.config/awesome
ln -fsv $DIR"/config/awesome/rc.lua" ~/.config/awesome/rc.lua
ln -fsv /etc/xdg/awesome/debian ~/.config/awesome/

sudo ln -fsv $DIR"/themes/takeontom" /usr/share/awesome/themes/

